version: "3.7"
services:
    {{cookiecutter.service_name}}:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile.dev
        ports:
            - {{cookiecutter.local_port}}:{{cookiecutter.container_port}}
        volumes:
            - ..:/usr/src/app
        command: sleep infinity