FROM {{cookiecutter.docker_base_image}}



ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY="host.docker.internal:0"


# Visual Studio Code Live Share in Container
RUN apt update && apt-get install git-core wget curl sqlite3 apt-utils -o APT::Install-Suggests=0 -y --no-install-recommends --no-install-suggests
RUN wget -O ~/vsls-reqs https://aka.ms/vsls-linux-prereq-script && chmod +x ~/vsls-reqs && ~/vsls-reqs

# Poerty
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
# RUN /bin/bash -c "source $HOME/.poetry/env"

# Install Python dependencies
COPY .config/.bashrc /root/
WORKDIR /usr/src/app
COPY poetry.lock ./
COPY pyproject.toml ./
RUN /root/.poetry/bin/poetry install
RUN /root/.poetry/bin/poetry config --local virtualenvs.in-project true
COPY . .


EXPOSE {{cookiecutter.container_port}}

# CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000" ]
